### 

// 회원가입
POST http://localhost:8000/user/signup
Content-Type: application/json

{
    "email":"timeli@naver.com",
    "password":"jason1234!"
}

###
// 아이디 중복 검사
POST  http://localhost:8000/user/idCheck
Content-Type: application/json

{
    "email":"timeli1@naver.com"
}

###
// 로그인
POST http://15.164.50.132:8000/user/login
Content-Type: application/json

{
    "email":"timeli@naver.com",
    "password":"jason1234!"
}

###
// 인증 메일
POST http://15.164.50.132:8000/user/emailAuth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTcwMjE3N30.HxqdcEkGQHXQzAIB23ZanaeJPgVGkYYe609w03QUnQ0
Content-Type: application/json

###
// 인증 체크
GET http://15.164.50.132:8000/user/checkEmailAuth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTcwMjE3N30.HxqdcEkGQHXQzAIB23ZanaeJPgVGkYYe609w03QUnQ0
Content-Type: application/json

{
    "emailAuth": 3669
}

###
// 비밀번호 변경
PATCH  http://15.164.50.132:8000/user/changePassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTcwMjE3N30.HxqdcEkGQHXQzAIB23ZanaeJPgVGkYYe609w03QUnQ0
Content-Type: application/json

{
    "password": "jason1234"
}